### ISSUE TITLE
racattack: Is a directory

### ISSUE THREAD

**Issue by nviogne** [racattack/racattack-ansible-oracle#3]
Hello,
Thanks for this cool project!
When doing vagrant up I have this issue : 
   collabn1: /media/stagefiles/run_ansible_playbook.sh: line 19: /media/stagefiles/ansible-oracle/group_vars/racattack: Is a directory
Is there a solution for this problem?
Thank you

**Comment by nviogne** [comment]
OK I think that I have found the probIem. I am going to try ansible-oracle v1.4.1 instead of 1.5. Some changes occured since this version.

**Comment by oravirt** [comment]
Hi,
This project is not really maintained anymore. 
But, if you want a `vagrant-vbox-rac` solution you could try https://github.com/oravirt/vagrant-vbox-rac, which is actively developed and maintained. It also follows https://github.com/oravirt/ansible-oracle more closely.

**Comment by nviogne** [comment]
OK thank you! I'm going to look at the vagrant-vbox-rac...
